#!/bin/sh
# this script will
#   i) Pull OpenFOAM+ with swak4Foam and PyFoam from docker hub if it does not exist in local environment
#  ii) Create  container with name of_v1906_plus_swak
# iii) PostProcessing Tool : paraview/paraFoam
#  iv) Image comes with already installed utility:
#      Midnight Commander, gnuplot
#   v) This script has been tested upto 1.12 docker version
#    Note: Docker daemon should be running before  launching script
# This script is a slight edit of the original script for the official OpenFOAM+-container
username="$USER"
user="$(id -u)"
home="${1:-$HOME}"

imageName="hfdresearch/swak4foamandpyfoam:latest-v1906"
containerName="of_v1906_plus_swak"
displayVar="$DISPLAY"
# find container already created are running:
echo "Following Docker containers are present on your system:"
echo "**************************************** "
docker ps -a

localPasswd=$(pwd)/localPasswd
getent passwd >$localPasswd

#creating docker container for OpenFOAM+ operation
echo "**************************************** "
echo "			"
echo "Creating Docker OpenFOAM+ with swak4Foam and PyFoam container ${containerName}"

docker run  -it -d --name ${containerName} --user=${user} \
       -e USER=${username} \
       -e QT_X11_NO_MITSHM=1 \
       -e DISPLAY=${displayVar} \
       -e QT_XKB_CONFIG_ROOT=/usr/share/X11/xkb                \
       --workdir="${home}" \
       --volume="${home}:${home}"  \
       --volume="/etc/group:/etc/group:ro"  \
       --volume="${localPasswd}:/etc/passwd:ro"  \
       --volume="/etc/shadow:/etc/shadow:ro"  \
       --volume="/etc/sudoers.d:/etc/sudoers.d:ro" \
       -v=/tmp/.X11-unix:/tmp/.X11-unix  ${imageName}  \
       /bin/bash --rcfile /opt/OpenFOAM/setImage_v1906+

echo "Container ${containerName} was created."

echo "**************************************************"
echo "Run the startSwakPyFoam script to launch container"
echo "**************************************************"
